#!/bin/sh

#
# Changelog entries are stored in the git tags, in MediaWiki format
# (I didn't use Markdown, because git eats the '#' needed for headings)
#

#
# Parameters
#
cd /Users/jmason888/git/BootUnlocker
baseDir=/Users/jmason888/git/BootUnlocker
outputDir=build/wiki
outputFile=$outputDir/ChangeLog.wiki

cd $baseDir

cat <<FOO > $outputFile
#labels Featured
#summary Change Log; autogenerated from git tags

FOO

(
  #
  # Extract git tags (in reverse order)
  # Get the text of the tags
  #
  git tag -l | sort -r | xargs -n 1 git tag -l -n100 | sed -e 's/^c0[^=]*===/\
===/;s/^ *//' 
  #

) | \
# Convert from MediaWiki to Google Code Wiki
pandoc -f mediawiki -t ./scripts/GoogleWiki.lua >> $outputFile

cd $outputDir
git commit -a -m "Automatic documentation update"
git push


